export const lectCopy = {
  lecturesTab: 'הרצאות בהכשרה',
  copyConfirmLink: 'העתק קישור אישור',
  linkCopied: 'הקישור הועתק.',
  editTime: 'עריכת מועד',
  cancelFlowTitle: 'ביטול הרצאה',
  newTimeSaved: 'ההרצאה שובצה מחדש. סטטוס האישור אופס.',
  cancelledNote: 'ההרצאה בוטלה. הזמן שהתפנה הפך לזמן גמיש בלו״ז.',
  checkSchedule: 'לבניית הלו״ז',
  conflictsFound: 'המועד החדש מתנגש עם רכיבים קשיחים:',
  pickAnother: 'יש לבחור מועד אחר.',
  noLectures: 'אין הרצאות חוץ בהכשרה.',
  addLectureTitle: 'הוספת הרצאת חוץ',
  pickLecturer: 'בחירת מרצה',
  newLecturerInline: 'יצירת פרופיל מרצה חדש',
  lectureTitleLabel: 'נושא ההרצאה',
  warnBeforeLabel: 'התראה אם אין אישור הגעה',
  customMinutes: 'דקות לפני',
  lectureAdded: 'ההרצאה נוספה לטיוטה. תזכורת תישלח למרצה 24 שעות לפני.',
  editLecturer: 'עריכת מרצה',
  addLecturer: 'הוספת מרצה',
  lecturerSaved: 'פרופיל המרצה נשמר.',
  typesHint: 'ניתן להזין מספר נושאים מופרדים בפסיק.',
  confirmThanks: 'תודה! אישור ההגעה נקלט.',
  confirmInvalid: 'הקישור אינו תקין או שפג תוקפו.',
  confirmFor: 'אישור הגעה עבור',
  reminderAt: (t: string) => `תזכורת נשלחה: ${t}`
} as const
